#!/bin/sh

case $BLOCK_BUTTON in
#	1) setsid "$TERMINAL" -e pulsemixer & ;;
	1) st -n volume -e pulsemixer & ;;
	2) pulsemixer --toggle-mute ;;
	4) pulsemixer --change-volume +5 ;;
	5) pulsemixer --change-volume -5 ;;
	3) pgrep -x dunst >/dev/null && notify-send "<b>📢 Volume module:</b>
- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change."
esac

[ "$(pulsemixer --get-mute)" = "1" ] && printf "%s \\n" "Muted" && exit

vol=$(pulsemixer --get-volume | awk '{print $1}')

if [ "$vol" -gt "70" ]; then
	icon="&#1F50A; "
elif [ "$vol" -lt "30" ]; then
	icon="&#1F508; "
else
	icon="&#1F509; "
fi

#printf "%s %s%%\\n" "&#1F509" "$vol"
printf "%s %s\\n" "Vol: " "$vol"
